"""added reason column for break

Revision ID: 6ee27155b4d1
Revises: 77509c44eeb4
Create Date: 2024-09-05 15:50:53.370166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ee27155b4d1'
down_revision: Union[str, None] = '77509c44eeb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('breaks', sa.Column('reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('breaks', 'reason')
    # ### end Alembic commands ###
