"""init table

Revision ID: 750466223264
Revises: 
Create Date: 2024-09-05 13:48:20.889079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '750466223264'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_breaks_id', table_name='breaks')
    op.drop_table('breaks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breaks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('attendance_id', sa.INTEGER(), nullable=True),
    sa.Column('start_break', sa.DATETIME(), nullable=True),
    sa.Column('end_break', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_breaks_id', 'breaks', ['id'], unique=False)
    # ### end Alembic commands ###
