"""added breaks table

Revision ID: 77509c44eeb4
Revises: 750466223264
Create Date: 2024-09-05 15:35:13.311631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77509c44eeb4'
down_revision: Union[str, None] = '750466223264'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('start_day', sa.DateTime(), nullable=True))
    op.add_column('attendances', sa.Column('end_day', sa.DateTime(), nullable=True))
    op.drop_column('attendances', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('status', sa.VARCHAR(), nullable=True))
    op.drop_column('attendances', 'end_day')
    op.drop_column('attendances', 'start_day')
    # ### end Alembic commands ###
